import React, {useEffect, useState} from 'react';
import {ActivityIndicator, Pressable, StatusBar, StyleSheet, Text, View} from 'react-native';
import {ArrowLeft, MicOff, MoreVertical, PhoneOff, Radio, ShieldCheck, Sparkles, Volume2} from 'lucide-react-native';
import {Gradient} from '../../components/home/HomeDecor';
import ProfileAvatar from '../../components/home/ProfileAvatar';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function AudioRoomScreen({navigation, route}) {
const person = route.params?.person || {};
  const isDemo = route.params?.isDemo === true;
  const [joined, setJoined] = useState(false);
  const [busy, setBusy] = useState(false);
  useEffect(() => {
    if (!isDemo) return undefined;
    const timer = setTimeout(() => setBusy(true), 2000);
    return () => clearTimeout(timer);
  }, [isDemo]);
  const name = person.nickname || 'MILO member';
  return <SafeAreaView style={styles.screen}>
    <StatusBar barStyle="light-content" backgroundColor="#090A23" />
    <View style={styles.topGlow} /><View style={styles.sideGlow} />
    <View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.iconButton}><ArrowLeft size={22} color="#F4EFFF" /></Pressable><View><Text style={styles.headerTitle}>Audio Room</Text><Text style={styles.private}><ShieldCheck size={10} color="#3DEB9A" /> Private</Text></View><Pressable style={styles.iconButton}><MoreVertical size={21} color="#F4EFFF" /></Pressable></View>
    <View style={styles.hero}><View style={styles.outerRing}><View style={styles.midRing}><View style={styles.avatar}><ProfileAvatar {...(person.avatarStyle || person)} name={name} photoUrl={person.photoUrl} /><View style={styles.onlineDot} /></View></View></View><View style={styles.waveRow}><Radio size={34} color="#A850FF" /><Radio size={34} color="#A850FF" /></View><Text style={styles.name}>{name}</Text><Text style={styles.waiting}>{busy ? name + ' is busy now' : joined ? 'You are connected' : 'Waiting for you to join'}</Text></View>
    <View style={styles.statusCard}><Gradient from="#2F1A69" to="#171033" radius={16} /><Sparkles size={19} color="#C361FF" fill="#C361FF" /><Text style={styles.statusText}>{joined ? 'Audio room is live' : 'Preparing your audio room'}</Text><View style={styles.dots}><View style={styles.dot}/><View style={styles.dot}/><View style={styles.dot}/></View></View>
    <View style={styles.members}><View style={styles.member}><View style={styles.memberAvatar}><ProfileAvatar name="You" /></View><Text style={styles.memberLabel}>You</Text></View><Radio size={24} color="#BD5DFF" /><View style={styles.member}><View style={styles.memberAvatar}><ProfileAvatar {...(person.avatarStyle || person)} name={name} photoUrl={person.photoUrl} /><View style={styles.memberOnline}/></View><Text numberOfLines={1} style={styles.memberLabel}>{name}</Text></View></View>
    <View style={styles.matchingStatus}>{isDemo && !busy && <ActivityIndicator size="small" color="#C364FF" />}<Text style={styles.matchingText}>{busy ? 'Connecting you with another person…' : isDemo ? 'Checking room availability…' : 'Be kind. Keep it comfortable.'}</Text></View>
    <View style={styles.controls}><Pressable style={styles.control}><MicOff size={21} color="#E7DFFD" /><Text style={styles.controlText}>Mic Off</Text></Pressable><Pressable style={styles.control}><Volume2 size={21} color="#E7DFFD" /><Text style={styles.controlText}>Speaker</Text></Pressable><Pressable disabled={busy} onPress={() => setJoined(value => !value)} style={[styles.join, busy && styles.joinBusy]}><Gradient from="#E85BFF" to="#7725F3" radius={28} /><PhoneOff size={23} color="#FFFFFF" /><Text style={styles.joinText}>{joined ? 'Leave' : 'Join Room'}</Text></Pressable><Pressable style={styles.control}><Sparkles size={21} color="#E7DFFD" /><Text style={styles.controlText}>Effects</Text></Pressable></View>
  </SafeAreaView>;
}
const styles = StyleSheet.create({screen:{flex:1,backgroundColor:'#090A23',paddingHorizontal:16},topGlow:{position:'absolute',top:-90,left:-48,width:210,height:210,borderRadius:110,backgroundColor:'#4B238B',opacity:.62},sideGlow:{position:'absolute',top:88,right:-110,width:250,height:430,borderRadius:140,backgroundColor:'#26115C',opacity:.5},header:{height:70,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},iconButton:{width:34,height:34,borderRadius:18,backgroundColor:'rgba(44,35,90,.7)',borderWidth:1,borderColor:'#3D3471',alignItems:'center',justifyContent:'center'},headerTitle:{fontFamily:'Poppins-SemiBold',fontSize:14,color:'#FFF',textAlign:'center'},private:{fontSize:9,color:'#A79BC8',textAlign:'center'},hero:{alignItems:'center',marginTop:23},outerRing:{width:137,height:137,borderRadius:69,backgroundColor:'rgba(157,62,255,.2)',borderWidth:2,borderColor:'#6E33D1',alignItems:'center',justifyContent:'center'},midRing:{width:116,height:116,borderRadius:58,borderWidth:4,borderColor:'#A94EFF',padding:5},avatar:{flex:1,borderRadius:52,overflow:'hidden'},onlineDot:{position:'absolute',right:3,bottom:4,width:14,height:14,borderRadius:7,backgroundColor:'#2BEF9C',borderWidth:2,borderColor:'#29135F'},waveRow:{position:'absolute',top:58,width:230,flexDirection:'row',justifyContent:'space-between'},name:{fontFamily:'Poppins-SemiBold',fontSize:20,color:'#FFF',marginTop:14},waiting:{fontSize:11,color:'#A79BC8',marginTop:-3},statusCard:{height:64,marginTop:17,borderWidth:1,borderColor:'#6848B8',borderRadius:16,overflow:'hidden',flexDirection:'row',alignItems:'center',paddingHorizontal:18,gap:9},statusText:{fontFamily:'Poppins-Medium',fontSize:12,color:'#F2EDFF'},dots:{position:'absolute',bottom:10,left:0,right:0,flexDirection:'row',justifyContent:'center',gap:6},dot:{width:7,height:7,borderRadius:4,backgroundColor:'#B15EFF'},members:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:30,marginTop:28},member:{alignItems:'center',width:70},memberAvatar:{width:55,height:55,borderRadius:28,padding:3,borderWidth:2,borderColor:'#A851F6',overflow:'visible'},memberOnline:{position:'absolute',right:0,bottom:0,width:10,height:10,borderRadius:5,backgroundColor:'#32E997'},memberLabel:{fontSize:10,color:'#FFF',marginTop:5},matchingStatus:{height:28,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:19},matchingText:{fontSize:10,color:'#B4A8CF'},controls:{position:'absolute',left:16,right:16,bottom:25,height:74,borderRadius:18,borderWidth:1,borderColor:'#3D3568',backgroundColor:'rgba(29,23,62,.9)',flexDirection:'row',alignItems:'center',justifyContent:'space-around'},control:{alignItems:'center',gap:4,width:52},controlText:{fontSize:8,color:'#DDD4EE'},join:{height:55,minWidth:92,borderRadius:28,overflow:'hidden',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:5},joinBusy:{opacity:.5},joinText:{fontFamily:'Poppins-Medium',fontSize:10,color:'#FFF'}});
